meta_product_name: "Speechless"
meta_title: "Speechless - discover the meaning behind speeches"
meta_description: "Speechless is the world's first platform for discussing and understanding the content of past and present speeches."
meta_image: "cover.png" # should exist in `app/assets/images/`
meta_og_image: "og-image.png"
